/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package programacion1.twitter_clone;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author Samuuel Kono Peralta
 */
public class PanelTwittear extends javax.swing.JPanel {
    String Username = "";
    int UID = 0;
    /**
     * Creates new form PanelTwittear
     */
    public PanelTwittear(String Username) {
        this.Username = Username;
        initComponents();
        this.Userlabel.setText(this.Username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Userlabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TwittearBody = new javax.swing.JTextArea();
        SendBtn = new javax.swing.JButton();

        Userlabel.setText("Username");

        TwittearBody.setColumns(20);
        TwittearBody.setRows(5);
        jScrollPane1.setViewportView(TwittearBody);

        SendBtn.setText("Send");
        SendBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SendBtnMouseClicked(evt);
            }
        });
        SendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SendBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SendBtn)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Userlabel)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Userlabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SendBtn)
                .addContainerGap(9, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SendBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SendBtnActionPerformed

    private void SendBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SendBtnMouseClicked
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
            
            Connection con2 = DriverManager.getConnection("jdbc:mysql://localhost:3306/users", "root", "root");
            PreparedStatement coman2 = con2.prepareStatement("SELECT * FROM users WHERE Username = ?");
            
            coman2.setString(1, this.Username);
            ResultSet rs = coman2.executeQuery();
            if(rs.next()){
                this.UID = rs.getInt("UserID");
            }
            
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/users", "root", "root");
            PreparedStatement comando = con.prepareStatement("INSERT INTO twits (Username, UserID, TwitBody, Likes, Dislikes) VALUES (?, ?, ?, 0, 0);");
            
            comando.setString(1, this.Username);
            comando.setInt(2, this.UID);
            comando.setString(3, this.TwittearBody.getText());
            comando.executeUpdate();
            this.TwittearBody.setText("");
            
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_SendBtnMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SendBtn;
    private javax.swing.JTextArea TwittearBody;
    private javax.swing.JLabel Userlabel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    
}

