/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package programacion1.twitter_clone;

/**
 *
 * @author Samuuel Kono Peralta
 */
public class PanelTwitt extends javax.swing.JPanel {
    public int Likes = 0;
    public int Dislikes = 0;
    

    /**
     * Creates new form PanelTwitt
     */
    public PanelTwitt() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        UserLabel = new javax.swing.JLabel();
        LikeButton = new javax.swing.JButton();
        DislikeButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TwitBodyTxt = new javax.swing.JTextPane();
        LikeLabel = new javax.swing.JLabel();
        DislikeLabel = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        UserLabel.setText("Username");

        LikeButton.setText("Like");
        LikeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LikeButtonMouseClicked(evt);
            }
        });

        DislikeButton.setText("Dislike");

        jScrollPane3.setViewportView(TwitBodyTxt);

        LikeLabel.setText("0");

        DislikeLabel.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(UserLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(16, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LikeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LikeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DislikeButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DislikeLabel)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(UserLabel)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LikeButton)
                    .addComponent(DislikeButton)
                    .addComponent(LikeLabel)
                    .addComponent(DislikeLabel))
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void LikeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LikeButtonMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_LikeButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DislikeButton;
    private javax.swing.JLabel DislikeLabel;
    private javax.swing.JButton LikeButton;
    private javax.swing.JLabel LikeLabel;
    private javax.swing.JTextPane TwitBodyTxt;
    private javax.swing.JLabel UserLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
    public void setTwitBodyTxt(String texto){
        this.TwitBodyTxt.setText(texto);
    }
    
    public void setTwitLikes(int likes, int dislikes){
        this.LikeLabel.setText(Integer.toString(likes));
        this.Likes = likes;
        this.DislikeLabel.setText(Integer.toString(dislikes));
        this.Dislikes = dislikes;
    }
    
    public void setUser(String User){
        this.UserLabel.setText(User);
    }

}